version: '3.8'

services:
  api:
    build: .
    links:
      - "db:projectdb"
    environment:
      - ACL_DB_HOST=projectdb
    ports:
      - "6011:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7.38
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=acl
    volumes:
      - /home/authfix/samples:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin:5.1.3-apache
    restart: unless-stopped
    environment:
      - PMA_USER=root
      - PMA_HOST=acldb
      - PMA_PASSWORD=mysql
    ports:
      - "6010:80"
    links:
      - "db:acldb"
    